# Path to your oh-my-zsh installation 
export ZSH=$HOME/.oh-my-zsh

# Use the 'powerlevel9k' theme
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vi_mode battery time)
ZSH_THEME="powerlevel9k/powerlevel9k"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Show red dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Show command execution timestamps in history output
HIST_STAMPS="mm/dd/yyyy"

# Use a special ZSH custom directory
ZSH_CUSTOM=$HOME/.zshrc.d/

cool_plugins=(command-not-found cp osx)
workflow_plugins=(brew brew-cask bundler battery extract git git-extras)
vim_plugins=(vi_mode vundle)
navigation_plugins=(z)
ui_plugins=(catimg colored-man-pages tmux)
ruby_plugins=(gem rails rake-fast ruby rvm)

plugins=($cool_plugins $workflow_plugins $vim_plugins $navigation_plugins $ui_plugins $ruby_plugins)

# Use configuration

# Prefer homebrew versions of binaries over the system-standard binaries...
export PATH=/opt/local/bin:/usr/local/bin:$PATH
# Add manpages from homebrew to the MANPATH
export MANPATH=/usr/local/man:/opt/local/man:$MANPATH

# Load oh-my-zsh!
source $ZSH/oh-my-zsh.sh
